[package]
name = "midi_key_mapper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
midir = { git = "https://github.com/Boddlnagg/midir", branch = "master" }
